package ui.beans.veg;

import static mod.Event.DROUGHT;
import static mod.Event.FROST;
import mod.GameLogic;

public class ParsnipBean extends javax.swing.JPanel {

    public ParsnipBean() {
        initComponents();
    }
    
    public int getPoints(boolean glasshouse)
    {
        int points = 0;
        int middle = 0;
        int bonus = 0;
        
        if (calcBean1.getCount() > 0 && calcBean3.getCount() > 0)
        {
            if (calcBean1.getCount() > calcBean3.getCount())
            {
                points = calcBean3.getCount();
            }
            else
            {
                points = calcBean1.getCount();
            }
            
            if (calcBean2.getCount() > 0)
            {
                if (points > calcBean2.getCount())
                {
                    middle = (calcBean2.getCount() * 2);
                }
                else
                {
                    middle = (points * 2);
                }
            }
        }
        
        if (glasshouse == false)
        {
            switch (GameLogic.getInstance().getCurrEvent())
            {
                case DROUGHT -> bonus = -points;
                case FROST -> bonus = 0;
            }
        }
        
        points *= 3;
        
        return points + middle + bonus; 
    }

    public int getAmount()
    {
        if (calcBean1.getCount() > 0 && calcBean3.getCount() > 0)
        {
            if (calcBean1.getCount() > calcBean3.getCount())
            {
                return calcBean3.getCount();
            }
            else
            {
                return calcBean1.getCount();
            }
        }
        
        return 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        calcBean1 = new ui.beans.VegBean();
        calcBean2 = new ui.beans.VegBean();
        calcBean3 = new ui.beans.VegBean();

        setLayout(new java.awt.GridBagLayout());

        calcBean1.setVegetableName("Parsnip [1/3]");
        calcBean1.setVegetablePath("/res/parsnip_1.png");
        add(calcBean1, new java.awt.GridBagConstraints());

        calcBean2.setVegetableName("Parsnip [2/3]");
        calcBean2.setVegetablePath("/res/parsnip_2.png");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(calcBean2, gridBagConstraints);

        calcBean3.setVegetableName("Parsnip [3/3]");
        calcBean3.setVegetablePath("/res/parsnip_3.png");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(calcBean3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.beans.VegBean calcBean1;
    private ui.beans.VegBean calcBean2;
    private ui.beans.VegBean calcBean3;
    // End of variables declaration//GEN-END:variables
}
