package ui.beans;

import mod.Player;

public class PlayerScorePanel extends javax.swing.JPanel
{
  
    public static final String PROP_PLAYER_REMOVED = "removedPlayer";
    
    private final Player player;
    
    public PlayerScorePanel(Player player) {
        initComponents();
        
        this.player = player;
        
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, player.getNickname(),
                         javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
                         javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                         new java.awt.Font("Segoe UI", 1, 18))); 
        
        lblPoints.setText(player.getPoints() + " Points");
        btnAction.setText(player.getPoints() > 0 ? "Reset" : "Remove");
    }

    public Player getPlayer()
    {
        return player;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAction = new javax.swing.JButton();
        lblPoints = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nickname", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        btnAction.setText("Reset");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        add(btnAction, java.awt.BorderLayout.LINE_END);

        lblPoints.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPoints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoints.setText("100 Points");
        add(lblPoints, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        if (player.getPoints() > 0)
        {
            player.setPoints(0);
            lblPoints.setText(player.getPoints() + " Points");
            btnAction.setText("Remove");
        }
        else
        {
            firePropertyChange(PROP_PLAYER_REMOVED, player, null);
        }
    }//GEN-LAST:event_btnActionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JLabel lblPoints;
    // End of variables declaration//GEN-END:variables
}
