package ui;

import mod.Event;

public class EventPanel extends javax.swing.JPanel {

    public EventPanel() {
        initComponents();
        btnRandom.setVisible(false);
    }

    public Event getSelectedEvent()
    {
        if (btnDrougth.isSelected())
        {
            return Event.DROUGHT;
        }
        else if (btnFrost.isSelected())
        {
            return Event.FROST;
        }
        else if (btnMoleCricket.isSelected())
        {
            return Event.MOLECRICKET;
        }
        else
        {
            return null;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnFrost = new javax.swing.JToggleButton();
        btnDrougth = new javax.swing.JToggleButton();
        btnMoleCricket = new javax.swing.JToggleButton();
        btnRandom = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(btnFrost);
        btnFrost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/frost.png"))); // NOI18N
        btnFrost.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Frost", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        btnFrost.setMaximumSize(new java.awt.Dimension(200, 200));
        btnFrost.setMinimumSize(new java.awt.Dimension(200, 200));
        btnFrost.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(btnFrost, gridBagConstraints);

        buttonGroup1.add(btnDrougth);
        btnDrougth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/drought.png"))); // NOI18N
        btnDrougth.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Drought", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        btnDrougth.setMaximumSize(new java.awt.Dimension(200, 200));
        btnDrougth.setMinimumSize(new java.awt.Dimension(200, 200));
        btnDrougth.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(btnDrougth, gridBagConstraints);

        buttonGroup1.add(btnMoleCricket);
        btnMoleCricket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/mole_cricket.png"))); // NOI18N
        btnMoleCricket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mole Cricket", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        btnMoleCricket.setMaximumSize(new java.awt.Dimension(200, 200));
        btnMoleCricket.setMinimumSize(new java.awt.Dimension(200, 200));
        btnMoleCricket.setPreferredSize(new java.awt.Dimension(200, 200));
        btnMoleCricket.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(btnMoleCricket, gridBagConstraints);

        buttonGroup1.add(btnRandom);
        btnRandom.setText("RAND");
        btnRandom.setMaximumSize(new java.awt.Dimension(200, 200));
        btnRandom.setMinimumSize(new java.awt.Dimension(200, 200));
        btnRandom.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(btnRandom, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDrougth;
    private javax.swing.JToggleButton btnFrost;
    private javax.swing.JToggleButton btnMoleCricket;
    private javax.swing.JToggleButton btnRandom;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
