package ui;

import mod.Player;
import ui.beans.veg.CarrotBean;
import ui.beans.veg.CeleryBean;
import ui.beans.veg.GingerBean;
import ui.beans.veg.ParsnipBean;
import ui.beans.veg.PotatoBean;
import ui.beans.veg.RadishBean;
import ui.beans.veg.BeetRootBean;
import ui.beans.veg.TurnipBean;

public class HarvestPanel extends javax.swing.JPanel {

    private final Player player;
    
    public HarvestPanel(Player player) {
        initComponents();
        
        this.player = player;
        
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Harvesting: " + player.getNickname(),
                         javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
                         javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                         new java.awt.Font("Segoe UI", 1, 18))); 
    }

    public void applyPoints()
    {
        this.player.setPoints(player.getPoints() + potatoBean1.getPoints(btnGlasshouse.isSelected()));
        this.player.setPoints(player.getPoints() + radishBean1.getPoints(btnGlasshouse.isSelected()));
        this.player.setPoints(player.getPoints() + gingerBean1.getPoints(btnGlasshouse.isSelected()));
        this.player.setPoints(player.getPoints() + beetrootBean1.getPoints(btnGlasshouse.isSelected()));
        this.player.setPoints(player.getPoints() + turnipBean1.getPoints(btnGlasshouse.isSelected()));
        this.player.setPoints(player.getPoints() + celeryBean1.getPoints(btnGlasshouse.isSelected()));
        this.player.setPoints(player.getPoints() + parsnipBean1.getPoints(btnGlasshouse.isSelected()));
        this.player.setPoints(player.getPoints() + carrotBean1.getPoints(btnGlasshouse.isSelected()));
        
        // remember combo for final result
        this.player.addToBasket(PotatoBean.class, potatoBean1.getAmount());
        this.player.addToBasket(RadishBean.class, radishBean1.getAmount());
        this.player.addToBasket(GingerBean.class, gingerBean1.getAmount());
        this.player.addToBasket(BeetRootBean.class, beetrootBean1.getAmount());
        this.player.addToBasket(TurnipBean.class, turnipBean1.getAmount());
        this.player.addToBasket(CeleryBean.class, celeryBean1.getAmount());
        this.player.addToBasket(ParsnipBean.class, parsnipBean1.getAmount());
        this.player.addToBasket(CarrotBean.class, carrotBean1.getAmount());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnGlasshouse = new javax.swing.JToggleButton();
        potatoBean1 = new ui.beans.veg.PotatoBean();
        radishBean1 = new ui.beans.veg.RadishBean();
        gingerBean1 = new ui.beans.veg.GingerBean();
        beetrootBean1 = new ui.beans.veg.BeetRootBean();
        turnipBean1 = new ui.beans.veg.TurnipBean();
        celeryBean1 = new ui.beans.veg.CeleryBean();
        parsnipBean1 = new ui.beans.veg.ParsnipBean();
        carrotBean1 = new ui.beans.veg.CarrotBean();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Harvesting: NICKNAME"));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnGlasshouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/glasshouse_unselected.png"))); // NOI18N
        btnGlasshouse.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Glasshouse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        btnGlasshouse.setContentAreaFilled(false);
        btnGlasshouse.setRolloverEnabled(false);
        btnGlasshouse.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/glasshouse.png"))); // NOI18N
        jPanel1.add(btnGlasshouse, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(potatoBean1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(radishBean1, gridBagConstraints);

        add(jPanel1);
        add(gingerBean1);
        add(beetrootBean1);
        add(turnipBean1);
        add(celeryBean1);
        add(parsnipBean1);
        add(carrotBean1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.beans.veg.BeetRootBean beetrootBean1;
    private javax.swing.JToggleButton btnGlasshouse;
    private ui.beans.veg.CarrotBean carrotBean1;
    private ui.beans.veg.CeleryBean celeryBean1;
    private ui.beans.veg.GingerBean gingerBean1;
    private javax.swing.JPanel jPanel1;
    private ui.beans.veg.ParsnipBean parsnipBean1;
    private ui.beans.veg.PotatoBean potatoBean1;
    private ui.beans.veg.RadishBean radishBean1;
    private ui.beans.veg.TurnipBean turnipBean1;
    // End of variables declaration//GEN-END:variables
}
