package ui;

import mod.Player;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import mod.GameLogic;
import ui.beans.PlayerScorePanel;

public class SetupPanel extends javax.swing.JPanel {

    public static final String PROP_PLAYERS_CHANGED = "changedPlayers";
    
    private final PropertyChangeListener removeListener = (PropertyChangeEvent evt) -> 
    {
        PlayerScorePanel p = (PlayerScorePanel) evt.getSource();
        p.removePropertyChangeListener(SetupPanel.this.removeListener);
        
        GameLogic.getInstance().removePlayer((Player) evt.getOldValue());
        updateView();
    };

    public SetupPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCreate = new javax.swing.JPanel();
        txtNickname = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        pnlPlayers = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlCreate.setBorder(javax.swing.BorderFactory.createTitledBorder("Nickname"));
        pnlCreate.setLayout(new java.awt.BorderLayout());

        txtNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicknameActionPerformed(evt);
            }
        });
        pnlCreate.add(txtNickname, java.awt.BorderLayout.CENTER);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlCreate.add(btnAdd, java.awt.BorderLayout.LINE_END);

        add(pnlCreate, java.awt.BorderLayout.NORTH);

        pnlPlayers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        pnlPlayers.setLayout(new javax.swing.BoxLayout(pnlPlayers, javax.swing.BoxLayout.PAGE_AXIS));
        add(pnlPlayers, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtNickname.getText().trim().isEmpty() == false)
        {
            GameLogic.getInstance().addPlayer(new Player(txtNickname.getText()));
            updateView();
        }
        
        txtNickname.setText(null);
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicknameActionPerformed
        if (txtNickname.getText().trim().isEmpty() == false)
        {
            GameLogic.getInstance().addPlayer(new Player(txtNickname.getText()));
            updateView();
        }
        
        txtNickname.setText(null);
    }//GEN-LAST:event_txtNicknameActionPerformed

    public void updateView()
    {
        int playersOld = pnlPlayers.getComponentCount();
        
        pnlPlayers.removeAll();
        
        for (Player player : GameLogic.getInstance().getPlayers())
        {
            PlayerScorePanel p = new PlayerScorePanel(player);
            pnlPlayers.add(p);
            p.addPropertyChangeListener(PlayerScorePanel.PROP_PLAYER_REMOVED, removeListener);
        }
        
        pnlPlayers.revalidate();
        pnlPlayers.repaint();
        
        firePropertyChange(PROP_PLAYERS_CHANGED, playersOld, pnlPlayers.getComponentCount());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JPanel pnlCreate;
    private javax.swing.JPanel pnlPlayers;
    private javax.swing.JTextField txtNickname;
    // End of variables declaration//GEN-END:variables
}
